# Building a Document-Term Matrix from scratch


In [ ]:
# install & import the libraries needed
!pip3 install pandas
!pip3 install scikit-learn
from typing import List
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# A mini corpus to play with
CORPUS = [
    'this is the first document',
    'this is the second document',
    'and this is the third document',
    'is this the first document ?'
]


In [ ]:
def tf(term: str, doc: str) -> int:
    ### TODO 1 ### 
    # count the frequency of term in doc. hint: str.count()
    tf = doc.count(term)
    tf = sum([
          1 if word == term  else 0 for word in doc.split(" ") 
    ])
    #print(tf)
    ##############
    return tf

In [ ]:
def build_dtm(corpus: List[str]) -> pd.DataFrame:
    ### TODO 2 ###
    # build a vocabulary of the given corpus - use nested list comprehension, str.split(" "),  set,  and list
    vocab: List[str] = list(set([term for doc in corpus for term in doc.split()])) #set 을 써서 list 로 변경 = 즉 중복을 제외한 고유한 단어만 가져온다 
    ##############
    #words = [word for doc in vocab for word in doc.split(" ")]
    ### TODO 3 ###
    # populate a dtm - get use of the tf function
    #vocab = list(set(words))
    print(vocab)
    
    dtm: List[List[int]] = [[tf(term, doc) for term in vocab] for doc in corpus]
    print(dtm)
       
      
    
    ##############
    # return dtm as a pandas dataframe (for better visualization of the columns)
    dtm = pd.DataFrame(data=dtm, columns=vocab)
    return dtm

In [ ]:
 # build a dtm from the corpus, and have a look at it
dtm = build_dtm(CORPUS)
print(dtm)

['first', 'second', 'is', 'the', 'third', 'and', 'this', '?', 'document']
[[1, 0, 2, 1, 0, 0, 1, 0, 1], [0, 1, 2, 1, 0, 0, 1, 0, 1], [0, 0, 2, 1, 1, 1, 1, 0, 1], [1, 0, 2, 1, 0, 0, 1, 1, 1]]
   first  second  is  the  third  and  this  ?  document
0      1       0   2    1      0    0     1  0         1
1      0       1   2    1      0    0     1  0         1
2      0       0   2    1      1    1     1  0         1
3      1       0   2    1      0    0     1  1         1


다음과 같은 결과가 나와야 합니다 (단어의 순서는 달라도 괜찮습니다):
```
   is  ?  first  and  document  this  the  second  third
0   2  0      1    0         1     1    1       0      0
1   2  0      0    0         1     1    1       1      0
2   2  0      0    1         1     1    1       0      1
3   2  1      1    0         1     1    1       0      0
```
(슬라이드에는 0또는 1로 카운트를 했지만, 튜토리얼에서는 그냥 카운트를 하겠습니다! (e.g. is가 두 개 포함되어 있다면 그냥 2로)

In [ ]:
# this will print out the similarities of the documents to each other
sim_matrix = cosine_similarity(dtm.to_numpy(), dtm.to_numpy())
print(sim_matrix)

[[1.         0.875      0.82495791 0.94280904]
 [0.875      1.         0.82495791 0.82495791]
 [0.82495791 0.82495791 1.         0.77777778]
 [0.94280904 0.82495791 0.77777778 1.        ]]


다음과 같은 결과가 나와야 합니다:
```
[[1.         0.875      0.82495791 0.94280904]
 [0.875      1.         0.82495791 0.82495791]
 [0.82495791 0.82495791 1.         0.77777778]
 [0.94280904 0.82495791 0.77777778 1.        ]]
```

## **TODO 4**: 마지막으로, 다음의 질문에 답해주세요.
> 위 `sim_matrix`를 보고 `dtm`의 어떤 문제를 발견할 수 있나요? (힌트: `CORPUS`에 있는 문장의 의미는 모두 동일한가요?)

In [ ]:
'''
의문형이나  평서문 이나 다른 의미인데 같은 유사도를 나타낸다.
this is  is 중복 으로 카운팅 

'''

'\nthis 랑 is  는 this 안에 is 라는 글자도 있어서 is 라는 글자가 두번 counting 이 된다.\n즉 부분적 글자 를 카운팅해서 빈도가 올라간다.\n'