In [ ]:
!pip3 install numpy
import numpy as np


In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# idf - term
b = np.array([1, 2, 3])

# "looping occurs in C instead of Python": faster than for loop
# https://numpy.org/doc/stable/user/basics.broadcasting.html
print(a * b)   # broadcast-multiply across columns
# __mul__


# row에 broadcast 하고 싶다면?
print((a.T * b).T)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
