In [ ]:
#import pandas ,numpy 

import pandas as pd 
import numpy as np 
df = pd.read_csv('/content/faults.csv')

In [ ]:
#data 확인 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1941 entries, 0 to 1940
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   X_Minimum              1941 non-null   int64  
 1   X_Maximum              1941 non-null   int64  
 2   Y_Minimum              1941 non-null   int64  
 3   Y_Maximum              1941 non-null   int64  
 4   Pixels_Areas           1941 non-null   int64  
 5   X_Perimeter            1941 non-null   int64  
 6   Y_Perimeter            1941 non-null   int64  
 7   Sum_of_Luminosity      1941 non-null   int64  
 8   Minimum_of_Luminosity  1941 non-null   int64  
 9   Maximum_of_Luminosity  1941 non-null   int64  
 10  Length_of_Conveyer     1941 non-null   int64  
 11  TypeOfSteel_A300       1941 non-null   int64  
 12  TypeOfSteel_A400       1941 non-null   int64  
 13  Steel_Plate_Thickness  1941 non-null   int64  
 14  Edges_Index            1941 non-null   float64
 15  Empt

In [ ]:
#데이터를 좀더 간편화 시킨다.
df_dataset = df[['X_Minimum','X_Maximum','Steel_Plate_Thickness','LogOfAreas',
                 'Pastry','Z_Scratch','Bumps']]
print("df_dataset.shape : ", df_dataset.shape)
print(df_dataset.info())

df_dataset.shape :  (1941, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1941 entries, 0 to 1940
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   X_Minimum              1941 non-null   int64  
 1   X_Maximum              1941 non-null   int64  
 2   Steel_Plate_Thickness  1941 non-null   int64  
 3   LogOfAreas             1941 non-null   float64
 4   Pastry                 1941 non-null   int64  
 5   Z_Scratch              1941 non-null   int64  
 6   Bumps                  1941 non-null   int64  
dtypes: float64(1), int64(6)
memory usage: 106.3 KB
None


In [ ]:
#train /test split
df_dataset = np.asarray(df_dataset, dtype = 'float32')

df_dataset_x = df_dataset[0:1,:-3] #독립변수
df_dataset_y = df_dataset[0:1,-3:] #종속변수

print(df_dataset_x.shape)
print(df_dataset_x)
print(df_dataset_y.shape)
print(df_dataset_y)

(1, 4)
[[42.     50.     80.      2.4265]]
(1, 3)
[[1. 0. 0.]]


In [ ]:
#정규 분포 평균 과 표준 편차 ,입력과 출력 크기 model parameter 정의
RND_MEAN = 0 
RND_STD = 1

input_cnt = df_dataset_x.shape[-1]
output_cnt = df_dataset_y.shape[-1]

weight = np.random.normal(RND_MEAN,RND_STD ,size = [input_cnt,output_cnt])
bias = np.random.normal(RND_MEAN,RND_STD ,size = [output_cnt])

print(weight)
print("------------------------")
print(bias)

[[-1.63422568  1.73628862 -1.22744773]
 [ 1.45546657  1.05902822 -0.58658452]
 [ 0.60876147  0.19848343  0.91643917]
 [-0.09725163 -0.02426195 -0.97762981]]
------------------------
[0.11033236 0.84182274 0.12787241]


In [ ]:
p_1 = np.matmul(df_dataset_x[0],weight[:,0]) + bias[0]
p_2 = np.matmul(df_dataset_x[0],weight[:,1]) + bias[1]
p_3 = np.matmul(df_dataset_x[0],weight[:,2]) + bias[2]

print(p_1,p_2,p_3)
result = np.matmul(df_dataset_x,weight) + bias
print(result)

52.71111917381142 142.53715856995402 -9.811243849775753
[[ 52.71111917 142.53715857  -9.81124385]]


In [ ]:

df = pd.read_csv('/content/faults_mini.csv')
df.info()
display(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   X_Minimum              10 non-null     int64
 1   Y_Minimum              10 non-null     int64
 2   Pixels_Areas           10 non-null     int64
 3   Steel_Plate_Thickness  10 non-null     int64
 4   Pastry                 10 non-null     int64
 5   Z_Scratch              10 non-null     int64
 6   K_Scatch               10 non-null     int64
dtypes: int64(7)
memory usage: 688.0 bytes


X_Minimum  Y_Minimum  Pixels_Areas  ...  Pastry  Z_Scratch  K_Scatch
0         42     270900           267  ...       1          0         0
1       1084     185575           108  ...       0          0         1
2       1109    1170194           130  ...       0          1         0
3        190     210936           132  ...       1          0         0
4        330     429227           264  ...       1          0         0
5         74     779144          1506  ...       1          0         0
6         51     585861           139  ...       0          1         0
7        397     604478           444  ...       0          1         0
8         43     366881          4048  ...       0          0         1
9         48     377537          3985  ...       0          0         1

[10 rows x 7 columns]

In [ ]:
df = np.asarray(df,dtype = 'float32')

In [ ]:
RND_MEAN = 0 
RND_STD = 1

input_cnt = df_dataset_x.shape[-1]
output_cnt = df_dataset_y.shape[-1]
print(input_cnt)
print(output_cnt)
weight = np.random.normal(RND_MEAN,RND_STD ,size = [input_cnt,output_cnt])
bias = np.random.normal(RND_MEAN,RND_STD ,size = [output_cnt])

print(weight)
print("------------------------")
print(bias)

4
3
[[-1.13960859 -0.44671865  1.25252174]
 [-0.23810162 -0.30914476  1.52251443]
 [ 1.46226325  1.1193944   0.59258303]
 [ 0.00534417  1.43559243 -0.44805302]]
------------------------
[-0.13125211 -1.10459337  0.52466304]


In [ ]:
#학습 데이터 셋과 테스트 셋 분류 
mb_size= 2 # 미니 배치 사이즈 
train_ratio = 0.8 #분리 비율 train set 이 80퍼센트 정도 나타 낸다.

print(df.shape)
print(df.shape[0] * train_ratio)

mb_step_count = df.shape[0] * train_ratio // mb_size #MB1 MB2 MB3 MB4
print(mb_step_count)



(10, 7)
8.0
4.0


In [ ]:
#test set index 
test_begin_index = mb_size * mb_step_count
print(test_begin_index)

#전체 데이터 셔플 
shuffle_map = np.arange(df.shape[0])
print(shuffle_map)
np.random.shuffle(shuffle_map)

print(shuffle_map)

8.0
[0 1 2 3 4 5 6 7 8 9]
[3 4 8 6 1 2 0 7 9 5]


In [ ]:
#미니 배치 사이즈를 shuffle map numpy 를 shuffle 하여 index 별로 나눔
mb_data_1 = df[shuffle_map[0:2]]
print(mb_data_1)
mb_data_2 = df[shuffle_map[2:4]]
print(mb_data_2)
mb_data_3 = df[shuffle_map[4:6]]
print(mb_data_3)
mb_data_4 = df[shuffle_map[6:8]]
print(mb_data_4)

[[1.90000e+02 2.10936e+05 1.32000e+02 1.50000e+02 1.00000e+00 0.00000e+00
  0.00000e+00]
 [3.30000e+02 4.29227e+05 2.64000e+02 1.50000e+02 1.00000e+00 0.00000e+00
  0.00000e+00]]
[[4.30000e+01 3.66881e+05 4.04800e+03 4.00000e+01 0.00000e+00 0.00000e+00
  1.00000e+00]
 [5.10000e+01 5.85861e+05 1.39000e+02 7.00000e+01 0.00000e+00 1.00000e+00
  0.00000e+00]]
[[1.084000e+03 1.855750e+05 1.080000e+02 4.000000e+01 0.000000e+00
  0.000000e+00 1.000000e+00]
 [1.109000e+03 1.170194e+06 1.300000e+02 1.750000e+02 0.000000e+00
  1.000000e+00 0.000000e+00]]
[[4.20000e+01 2.70900e+05 2.67000e+02 8.00000e+01 1.00000e+00 0.00000e+00
  0.00000e+00]
 [3.97000e+02 6.04478e+05 4.44000e+02 7.00000e+01 0.00000e+00 1.00000e+00
  0.00000e+00]]


In [ ]:
#독립변수 종속 변수 분할 
mb_data_1_x = mb_data_1[:,:-3]
mb_data_1_y = mb_data_1[:,-3:]
print(mb_data_1_x)
print(mb_data_1_y)
mb_data_2_x = mb_data_2[:,:-3]
mb_data_2_y = mb_data_2[:,-3:]

print(mb_data_2_x)
print(mb_data_2_y)
mb_data_3_x = mb_data_3[:,:-3]
mb_data_3_y = mb_data_3[:,-3:]

print(mb_data_3_x)
print(mb_data_3_y)
mb_data_4_x = mb_data_4[:,:-3]
mb_data_4_y = mb_data_4[:,-3:]

print(mb_data_4_x)
print(mb_data_4_y)

[[1.90000e+02 2.10936e+05 1.32000e+02 1.50000e+02]
 [3.30000e+02 4.29227e+05 2.64000e+02 1.50000e+02]]
[[1. 0. 0.]
 [1. 0. 0.]]
[[4.30000e+01 3.66881e+05 4.04800e+03 4.00000e+01]
 [5.10000e+01 5.85861e+05 1.39000e+02 7.00000e+01]]
[[0. 0. 1.]
 [0. 1. 0.]]
[[1.084000e+03 1.855750e+05 1.080000e+02 4.000000e+01]
 [1.109000e+03 1.170194e+06 1.300000e+02 1.750000e+02]]
[[0. 0. 1.]
 [0. 1. 0.]]
[[4.20000e+01 2.70900e+05 2.67000e+02 8.00000e+01]
 [3.97000e+02 6.04478e+05 4.44000e+02 7.00000e+01]]
[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
#mb_yhat predict 값 구하기 
mb1_yhat0 = np.matmul(mb_data_1_x,weight[:,0]) + bias[0]
mb1_yhat1 = np.matmul(mb_data_1_x,weight[:,1]) + bias[1]
mb1_yhat2 = np.matmul(mb_data_1_x,weight[:,2]) + bias[2]
print("MB1")
print(mb1_yhat0)
print(mb1_yhat1)
print(mb1_yhat2)


mb2_yhat0 = np.matmul(mb_data_2_x,weight[:,0]) + bias[0]
mb2_yhat1 = np.matmul(mb_data_2_x,weight[:,1]) + bias[1]
mb2_yhat2 = np.matmul(mb_data_2_x,weight[:,2]) + bias[2]

print("MB2")
print(mb2_yhat0)
print(mb2_yhat1)
print(mb2_yhat2)

mb3_yhat0 = np.matmul(mb_data_3_x ,weight[:,0]) + bias[0]
mb3_yhat1 = np.matmul(mb_data_3_x,weight[:,1]) + bias[1]
mb3_yhat2 = np.matmul(mb_data_3_x,weight[:,2])+ bias[2]

print("MB3")
print(mb3_yhat0)
print(mb3_yhat1)
print(mb3_yhat2)

mb4_yhat0 = np.matmul(mb_data_4_x ,weight[:,0]) + bias[0]
mb4_yhat1 = np.matmul(mb_data_4_x,weight[:,1]) + bias[1]
mb4_yhat2 = np.matmul(mb_data_4_x,weight[:,2])+ bias[2]

print("MB4")
print(mb4_yhat0)
print(mb4_yhat1)
print(mb4_yhat2)



MB1
[-209892.15544758 -427304.19839281]
[13596.45136167 27590.5581711 ]
[ -88233.73418267 -179690.03574444]
MB2
[-369338.94651938 -582667.97635612]
[20149.40921936 37962.63046636]
[-154330.86128096 -245736.96148627]
MB3
[ -186126.14766657 -1165023.2896915 ]
[11457.71837142 75492.40031887]
[ -76700.96681941 -489725.78652921]
MB4
[-269588.65518018 -602015.63537635]
[17393.14142389 38724.74488979]
[-113605.05394508 -253215.36324471]


In [ ]:
mbtotal = np.vstack((mb_data_1,mb_data_2,mb_data_3,mb_data_4))
#numpy 를 통한 vstack 으로 배치 데이터 하나로 만들기 
mb_total_train_x = mbtotal[:,:-3]
total = np.matmul(mb_total_train_x,weight) + bias
print(total)

[[ -209892.15544758    13596.45136167   -88233.73418267]
 [ -427304.19839281    27590.5581711   -179690.03574444]
 [ -369338.94651938    20149.40921936  -154330.86128096]
 [ -582667.97635612    37962.63046636  -245736.96148627]
 [ -186126.14766657    11457.71837142   -76700.96681941]
 [-1165023.2896915     75492.40031887  -489725.78652921]
 [ -269588.65518018    17393.14142389  -113605.05394508]
 [ -602015.63537635    38724.74488979  -253215.36324471]]


0.067082
